# -*- coding: utf-8 -*-
"""thesis_0318_modified.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GO85FWMt7GnsiHqKRbLMs_q3Q3818Sj-
"""

# ============================================
# Stage 0) Setup: mount drive + paths
# ============================================
from google.colab import drive
drive.mount("/content/drive")

import os, json, glob, shutil, random
from pathlib import Path
import numpy as np
import pandas as pd
import cv2

# ----------------------------
# Input paths
# ----------------------------
ORI_DIR   = "/content/drive/MyDrive/論文_new/need_label_ori"
LABEL_DIR = "/content/drive/MyDrive/論文_new/finish_label"

# ----------------------------
# Output dataset directory
# ----------------------------
DATASET_DIR = Path("/content/drive/MyDrive/論文_new/zp_seg_dataset_ratio")

IMG_OUT   = DATASET_DIR / "images"
ZP_OUT    = DATASET_DIR / "masks_zp_outter"
EMB_OUT   = DATASET_DIR / "masks_embryo_outer"

IMG_OUT.mkdir(parents=True, exist_ok=True)
ZP_OUT.mkdir(parents=True, exist_ok=True)
EMB_OUT.mkdir(parents=True, exist_ok=True)

print("[INFO] ORI_DIR   =", ORI_DIR)
print("[INFO] LABEL_DIR =", LABEL_DIR)
print("[INFO] DATASET   =", str(DATASET_DIR))

"""##Stage 1：掃描所有 json（你說的 40 張），建立清單並對應到影像"""

# ============================================
# Stage 1) Build labeled list from LABEL_DIR/*.json
# ============================================

IMG_EXTS = (".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff")

label_dir = Path(LABEL_DIR)
ori_dir   = Path(ORI_DIR)

json_files = sorted(label_dir.glob("*.json"))
print(f"[INFO] Found JSON files: {len(json_files)}")

assert len(json_files) > 0, "LABEL_DIR 沒有找到任何 json"

def find_image_by_stem(stem: str, ori_dir: Path) -> Path | None:
    """
    找 ORI_DIR 下與 stem 同名的影像（任一副檔名）
    """
    for ext in IMG_EXTS:
        p = ori_dir / f"{stem}{ext}"
        if p.exists():
            return p
    # 有些情況影像放子資料夾，若你有這種狀況再改成遞迴搜尋
    return None

rows = []
missing_img = 0

for jp in json_files:
    stem = jp.stem
    img_path = find_image_by_stem(stem, ori_dir)
    if img_path is None:
        missing_img += 1
        rows.append({
            "stem": stem,
            "json_path": str(jp),
            "image_path": "",
            "status": "missing_image"
        })
    else:
        rows.append({
            "stem": stem,
            "json_path": str(jp),
            "image_path": str(img_path),
            "status": "ok"
        })

df_list = pd.DataFrame(rows)
print("[INFO] Missing images:", missing_img)
display(df_list.head(10))

# 只保留 ok 的（真的能訓練的）
df_ok = df_list[df_list["status"] == "ok"].copy().reset_index(drop=True)
print("[INFO] Usable labeled pairs:", len(df_ok))

# 存 meta 清單（方便追蹤）
meta_path = DATASET_DIR / "meta.csv"
df_list.to_csv(meta_path, index=False, encoding="utf-8-sig")
print("[SAVED] meta.csv ->", meta_path)

"""##Stage 2：把 json 轉成 outer/inner mask，並把影像複製到 dataset"""

# ============================================
# Stage 2) LabelMe -> segmentation masks
# 目標：
#   1) 從 LabelMe json 讀取兩個 label：
#        - zp_outter
#        - embryo_outer
#   2) 轉成 binary mask
#   3) 存成訓練用 dataset
#   4) 自動檢查 label 別名，避免因拼字不同而整批配不到
# ============================================

from pathlib import Path
import json
import shutil
import numpy as np
import cv2
from PIL import Image, ImageDraw
import pandas as pd

# ----------------------------
# 路徑
# ----------------------------
ORI_DIR = Path("/content/drive/MyDrive/論文_new/need_label_ori")
LABEL_DIR = Path("/content/drive/MyDrive/論文_new/finish_label")
DATASET_DIR = Path("/content/drive/MyDrive/論文_new/zp_seg_dataset_ratio")

IMG_DIR = DATASET_DIR / "images"
ZP_MASK_DIR = DATASET_DIR / "masks_zp_outter"
EMBRYO_MASK_DIR = DATASET_DIR / "masks_embryo_outer"

IMG_DIR.mkdir(parents=True, exist_ok=True)
ZP_MASK_DIR.mkdir(parents=True, exist_ok=True)
EMBRYO_MASK_DIR.mkdir(parents=True, exist_ok=True)

# LabelMe label 名稱：主名稱 + 可接受別名
ZP_LABEL_CANDIDATES = ["zp_outter", "zp_outer"]
EMBRYO_LABEL_CANDIDATES = ["embryo_outer", "embryo_outter"]

print("[INFO] ZP labels      =", ZP_LABEL_CANDIDATES)
print("[INFO] Embryo labels  =", EMBRYO_LABEL_CANDIDATES)

# ----------------------------
# 工具函式
# ----------------------------
def polygon_area(points):
    pts = np.asarray(points, dtype=np.float32)
    if len(pts) < 3:
        return 0.0
    x = pts[:, 0]
    y = pts[:, 1]
    return 0.5 * abs(np.dot(x, np.roll(y, -1)) - np.dot(y, np.roll(x, -1)))

def shape_to_mask(img_h, img_w, points):
    img = Image.new("L", (img_w, img_h), 0)
    draw = ImageDraw.Draw(img)
    xy = [tuple(map(float, p)) for p in points]
    draw.polygon(xy, outline=1, fill=1)
    return np.array(img, dtype=np.uint8)

def pick_largest_shape_by_candidates(shapes, label_candidates):
    cand = []
    label_candidates = set(label_candidates)
    for sh in shapes:
        if sh.get("label") in label_candidates and len(sh.get("points", [])) >= 3:
            cand.append(sh)

    if len(cand) == 0:
        return None

    areas = [polygon_area(sh["points"]) for sh in cand]
    idx = int(np.argmax(areas))
    return cand[idx]

# ----------------------------
# 主流程
# ----------------------------
rows = []
json_files = sorted(LABEL_DIR.glob("*.json"))
print("json files:", len(json_files))

for js in json_files:
    stem = js.stem

    # 找原圖
    img_path = None
    for ext in [".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"]:
        p = ORI_DIR / f"{stem}{ext}"
        if p.exists():
            img_path = p
            break

    if img_path is None:
        rows.append({
            "stem": stem,
            "status": "missing_image"
        })
        continue

    try:
        with open(js, "r", encoding="utf-8") as f:
            ann = json.load(f)

        if "imageHeight" in ann and "imageWidth" in ann:
            h = int(ann["imageHeight"])
            w = int(ann["imageWidth"])
        else:
            img0 = cv2.imread(str(img_path))
            h, w = img0.shape[:2]

        shapes = ann.get("shapes", [])
        labels_found = sorted(list(set([sh.get("label", "") for sh in shapes])))

        shp_zp = pick_largest_shape_by_candidates(shapes, ZP_LABEL_CANDIDATES)
        shp_embryo = pick_largest_shape_by_candidates(shapes, EMBRYO_LABEL_CANDIDATES)

        if shp_zp is None or shp_embryo is None:
            rows.append({
                "stem": stem,
                "status": "missing_label",
                "labels_found": "|".join(labels_found),
                "has_zp_outter": shp_zp is not None,
                "has_embryo_outer": shp_embryo is not None
            })
            continue

        mask_zp = shape_to_mask(h, w, shp_zp["points"])
        mask_embryo = shape_to_mask(h, w, shp_embryo["points"])

        shutil.copy2(img_path, IMG_DIR / img_path.name)

        cv2.imwrite(str(ZP_MASK_DIR / f"{stem}.png"), (mask_zp * 255).astype(np.uint8))
        cv2.imwrite(str(EMBRYO_MASK_DIR / f"{stem}.png"), (mask_embryo * 255).astype(np.uint8))

        rows.append({
            "stem": stem,
            "status": "ok",
            "image_file": img_path.name,
            "zp_mask_file": f"{stem}.png",
            "embryo_mask_file": f"{stem}.png",
            "labels_found": "|".join(labels_found)
        })

    except Exception as e:
        rows.append({
            "stem": stem,
            "status": f"error: {str(e)}"
        })

df_build = pd.DataFrame(rows)
build_csv = DATASET_DIR / "build_summary.csv"
df_build.to_csv(build_csv, index=False, encoding="utf-8-sig")

print("saved:", build_csv)
display(df_build.head(20))
print(df_build["status"].value_counts(dropna=False))

if "missing_label" in set(df_build["status"]):
    print("\n[HINT] 若 missing_label 很多，請直接檢查 labels_found 欄位，確認你的 LabelMe 寫的是 zp_outter 還是 zp_outer。")

"""## Stage 3：建立 train/val split（80/20），輸出 split.csv"""

# ============================================
# Stage 3) train / val split (robust version)
# 目標：
#   1) 用共同 stem 配對 image / zp mask / embryo mask
#   2) 若 0 筆，直接印出診斷資訊，而不是在 train_test_split 才爆掉
# ============================================

from sklearn.model_selection import train_test_split
from pathlib import Path
import pandas as pd

DATASET_DIR = Path("/content/drive/MyDrive/論文_new/zp_seg_dataset_ratio")
IMG_DIR = DATASET_DIR / "images"
ZP_MASK_DIR = DATASET_DIR / "masks_zp_outter"
EMBRYO_MASK_DIR = DATASET_DIR / "masks_embryo_outer"

img_files = sorted([p for p in IMG_DIR.glob("*") if p.is_file()])
zp_files = sorted([p for p in ZP_MASK_DIR.glob("*.png") if p.is_file()])
embryo_files = sorted([p for p in EMBRYO_MASK_DIR.glob("*.png") if p.is_file()])

print("images count      :", len(img_files))
print("zp masks count    :", len(zp_files))
print("embryo masks count:", len(embryo_files))

img_map = {p.stem: p.name for p in img_files}
zp_map = {p.stem: p.name for p in zp_files}
embryo_map = {p.stem: p.name for p in embryo_files}

common_stems = sorted(set(img_map) & set(zp_map) & set(embryo_map))
print("common stems count:", len(common_stems))

if len(common_stems) == 0:
    print("\n[ERROR] 沒有任何可配對樣本")
    print("First 20 image stems  :", list(img_map.keys())[:20])
    print("First 20 zp stems     :", list(zp_map.keys())[:20])
    print("First 20 embryo stems :", list(embryo_map.keys())[:20])
    raise ValueError("usable samples = 0。請先檢查 Stage 2 的 build_summary.csv、label 名稱與檔名規則。")

rows = []
for stem in common_stems:
    rows.append({
        "stem": stem,
        "image_file": img_map[stem],
        "zp_mask_file": zp_map[stem],
        "embryo_mask_file": embryo_map[stem]
    })

df = pd.DataFrame(rows)
print("usable samples:", len(df))

if len(df) == 1:
    split_df = df.copy()
    split_df["split"] = "train"
else:
    train_df, val_df = train_test_split(df, test_size=0.2, random_state=42, shuffle=True)
    train_df = train_df.copy()
    val_df = val_df.copy()
    train_df["split"] = "train"
    val_df["split"] = "val"
    split_df = pd.concat([train_df, val_df], axis=0).reset_index(drop=True)

split_csv = DATASET_DIR / "split.csv"
split_df.to_csv(split_csv, index=False, encoding="utf-8-sig")

print("saved:", split_csv)
display(split_df.head())
print(split_df["split"].value_counts(dropna=False))

"""### Unet

##Stage 0：安裝與基本設定
"""

# ============================================
# Stage 0) Install + imports + paths
# ============================================

!pip -q install albumentations opencv-python

import os, time, math, random
from pathlib import Path

import numpy as np
import pandas as pd
import cv2

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

import albumentations as A

# ----------------------------
# Dataset path (前一步建立的比例資料集)
# ----------------------------
DATASET_DIR = Path("/content/drive/MyDrive/論文_new/zp_seg_dataset_ratio")
SPLIT_CSV   = DATASET_DIR / "split.csv"

assert SPLIT_CSV.exists(), f"找不到 split.csv: {SPLIT_CSV}"
print("[INFO] dataset =", DATASET_DIR)
print("[INFO] split   =", SPLIT_CSV)

# ----------------------------
# Training config
# ----------------------------
SEED = 42
IMG_SIZE = 512
BATCH_SIZE = 4
LR = 1e-3
EPOCHS = 80
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("[INFO] device =", DEVICE)

def seed_everything(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

seed_everything(SEED)

"""##Stage 1：Dataset / Dataloader（讀 image + outer/inner mask）"""

# ============================================
# Stage 1) Dataset + DataLoader
#   - reads split.csv
#   - loads RGB image
#   - loads zp_outter / embryo_outer masks (0/255)
#   - returns:
#       x: float tensor [3,H,W] in [0,1]
#       y: float tensor [2,H,W] (zp_outter, embryo_outer) in {0,1}
# ============================================

df = pd.read_csv(SPLIT_CSV)
required_cols = {"stem","split","image_file","zp_mask_file","embryo_mask_file"}
assert required_cols.issubset(df.columns), f"split.csv 欄位不符，缺少: {required_cols - set(df.columns)}"

train_df = df[df["split"]=="train"].reset_index(drop=True)
val_df   = df[df["split"]=="val"].reset_index(drop=True)

print("[INFO] train =", len(train_df), "val =", len(val_df))
display(train_df.head(3))

train_tf = A.Compose([       #train_tf: 包含 Resize、水平翻轉、垂直翻轉、隨機旋轉、平移縮放旋轉、亮度對比調整、模糊等增強。
    A.Resize(IMG_SIZE, IMG_SIZE),
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.2),
    A.RandomRotate90(p=0.3),
    A.ShiftScaleRotate(shift_limit=0.02, scale_limit=0.05, rotate_limit=10, p=0.5, border_mode=cv2.BORDER_REFLECT),
    A.RandomBrightnessContrast(p=0.7),
    A.GaussianBlur(blur_limit=(3,5), p=0.2),
], additional_targets={"mask2":"mask"})

val_tf = A.Compose([
    A.Resize(IMG_SIZE, IMG_SIZE),
], additional_targets={"mask2":"mask"})

class ZPRatioDataset(Dataset):
    def __init__(self, df: pd.DataFrame, root_dir: Path, tfm: A.Compose):
        self.df = df.reset_index(drop=True)
        self.root_dir = Path(root_dir)
        self.tfm = tfm
        self.img_dir = self.root_dir / "images"
        self.zp_dir = self.root_dir / "masks_zp_outter"
        self.embryo_dir = self.root_dir / "masks_embryo_outer"

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        r = self.df.iloc[idx]
        img_path = self.img_dir / r["image_file"]
        zp_path = self.zp_dir / r["zp_mask_file"]
        embryo_path = self.embryo_dir / r["embryo_mask_file"]

        img = cv2.imread(str(img_path), cv2.IMREAD_COLOR)
        if img is None:
            raise FileNotFoundError(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        m_zp = cv2.imread(str(zp_path), cv2.IMREAD_GRAYSCALE)
        m_embryo = cv2.imread(str(embryo_path), cv2.IMREAD_GRAYSCALE)
        if m_zp is None or m_embryo is None:
            raise FileNotFoundError(zp_path if m_zp is None else embryo_path)

        m_zp = (m_zp > 127).astype(np.uint8)
        m_embryo = (m_embryo > 127).astype(np.uint8)

        aug = self.tfm(image=img, mask=m_zp, mask2=m_embryo)
        img = aug["image"]
        m_zp = aug["mask"]
        m_embryo = aug["mask2"]

        x = torch.from_numpy(img).permute(2,0,1).float() / 255.0
        y = torch.from_numpy(np.stack([m_zp, m_embryo], axis=0)).float()
        return x, y, r["stem"]

train_ds = ZPRatioDataset(train_df, DATASET_DIR, train_tf)
val_ds   = ZPRatioDataset(val_df, DATASET_DIR, val_tf)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_ds, batch_size=1, shuffle=False, num_workers=2, pin_memory=True)

print("[INFO] dataloader ready")

"""## Stage 2：UNet 模型（純 PyTorch，2-channel 輸出）

建立 UNet 網路結構（Encoder–Decoder + skip connections）

輸出通道數設成 2：

channel 0：zp_outer mask

channel 1：zp_inner mask

把模型丟到 GPU/CPU

輸入

Stage 1 的影像 tensor（[B,3,H,W]）

輸出

模型輸出的 logits（[B,2,H,W]）

這步也不寫檔，核心是「定義模型長什麼樣」。
"""

# ============================================
# Stage 2) UNet (2-channel output: outer, inner)
# ============================================

class DoubleConv(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_ch, out_ch, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
        )

    def forward(self, x):
        return self.net(x)

class UNet(nn.Module):
    def __init__(self, in_ch=3, out_ch=2, base=32):
        super().__init__()
        self.enc1 = DoubleConv(in_ch, base)
        self.pool1 = nn.MaxPool2d(2)
        self.enc2 = DoubleConv(base, base*2)
        self.pool2 = nn.MaxPool2d(2)
        self.enc3 = DoubleConv(base*2, base*4)
        self.pool3 = nn.MaxPool2d(2)
        self.enc4 = DoubleConv(base*4, base*8)
        self.pool4 = nn.MaxPool2d(2)

        self.bottleneck = DoubleConv(base*8, base*16)

        self.up4 = nn.ConvTranspose2d(base*16, base*8, 2, stride=2)
        self.dec4 = DoubleConv(base*16, base*8)
        self.up3 = nn.ConvTranspose2d(base*8, base*4, 2, stride=2)
        self.dec3 = DoubleConv(base*8, base*4)
        self.up2 = nn.ConvTranspose2d(base*4, base*2, 2, stride=2)
        self.dec2 = DoubleConv(base*4, base*2)
        self.up1 = nn.ConvTranspose2d(base*2, base, 2, stride=2)
        self.dec1 = DoubleConv(base*2, base)

        self.out = nn.Conv2d(base, out_ch, kernel_size=1)

    def forward(self, x):
        e1 = self.enc1(x)
        e2 = self.enc2(self.pool1(e1))
        e3 = self.enc3(self.pool2(e2))
        e4 = self.enc4(self.pool3(e3))
        b  = self.bottleneck(self.pool4(e4))

        d4 = self.up4(b)
        d4 = torch.cat([d4, e4], dim=1)
        d4 = self.dec4(d4)

        d3 = self.up3(d4)
        d3 = torch.cat([d3, e3], dim=1)
        d3 = self.dec3(d3)

        d2 = self.up2(d3)
        d2 = torch.cat([d2, e2], dim=1)
        d2 = self.dec2(d2)

        d1 = self.up1(d2)
        d1 = torch.cat([d1, e1], dim=1)
        d1 = self.dec1(d1)

        logits = self.out(d1)  # [B,2,H,W]
        return logits

model = UNet(in_ch=3, out_ch=2, base=32).to(DEVICE)
print(model.__class__.__name__, "params =", sum(p.numel() for p in model.parameters())/1e6, "M")

"""##Stage 3：Loss（BCE + Dice）與評估指標（Dice）

定義訓練要最小化的損失函數：

BCEWithLogitsLoss：像素級分類（穩定）

Dice loss：強化重疊度（對 segmentation 常用，特別是前景比例小時）

最後加權合成 total_loss

定義評估指標：

dice_outer

dice_inner

dice_mean（兩者平均）

定義 evaluate()：在 val set 上跑一遍，回傳 loss 與 dice

輸入

model logits + ground truth masks

輸出

每個 epoch 的 validation metrics（數字）

仍然不寫檔，但它決定你「怎麼判斷模型好壞」
"""

# ============================================
# Stage 3) Loss & metrics
# ============================================

bce = nn.BCEWithLogitsLoss()

def dice_score(prob: torch.Tensor, target: torch.Tensor, eps=1e-6):
    """
    prob/target: [B,2,H,W] in [0,1] / {0,1}
    return: per-channel dice [2], and mean dice
    """
    # flatten
    B, C, H, W = prob.shape
    prob_f = prob.reshape(B, C, -1)
    targ_f = target.reshape(B, C, -1)
    inter = (prob_f * targ_f).sum(dim=2)
    union = prob_f.sum(dim=2) + targ_f.sum(dim=2)
    dice = (2*inter + eps) / (union + eps)  # [B,C]
    dice_c = dice.mean(dim=0)               # [C]
    return dice_c, dice_c.mean()

def dice_loss(logits: torch.Tensor, target: torch.Tensor):
    prob = torch.sigmoid(logits)
    _, dmean = dice_score(prob, target)
    return 1.0 - dmean

def total_loss(logits: torch.Tensor, target: torch.Tensor, alpha=0.5):
    """
    alpha: BCE vs Dice 權重
    """
    return alpha*bce(logits, target) + (1-alpha)*dice_loss(logits, target)

@torch.no_grad()
def evaluate(model, loader):
    model.eval()
    loss_sum = 0.0
    dice_outer_sum = 0.0
    dice_inner_sum = 0.0
    n = 0
    for x, y, _ in loader:
        x = x.to(DEVICE, non_blocking=True)
        y = y.to(DEVICE, non_blocking=True)
        logits = model(x)
        loss = total_loss(logits, y)
        prob = torch.sigmoid(logits)
        dice_c, _ = dice_score(prob, y)
        loss_sum += float(loss.item())
        dice_outer_sum += float(dice_c[0].item())
        dice_inner_sum += float(dice_c[1].item())
        n += 1
    return {
        "val_loss": loss_sum / max(n,1),
        "dice_outer": dice_outer_sum / max(n,1),
        "dice_inner": dice_inner_sum / max(n,1),
        "dice_mean": (dice_outer_sum + dice_inner_sum) / max(2*n,1),
    }

"""##Stage 4：Training loop（保存最佳模型 + 記錄 log）

正式訓練 EPOCHS 次：

訓練階段：對 train_loader 反向傳播更新權重

驗證階段：呼叫 evaluate() 算 val dice

用 dice_mean 當作選最佳模型的依據

若本 epoch 的 dice_mean > 歷史最佳，就存 checkpoint

把每個 epoch 的 train_loss / val_loss / dice 指標記錄起來

輸入

train_loader / val_loader

model

loss function

輸出（重要）

checkpoints/unet_best.pt：目前 val 表現最好的模型權重

checkpoints/train_log.csv：每個 epoch 的訓練/驗證指標紀錄
"""

# ============================================
# Stage 4) Train
# 完整的訓練迴圈，把前面定義好的模型 (UNet)、Loss、DataLoader 串起來，並且在每個 epoch 做訓練與驗證，最後保存最佳模型。
# ============================================

OPT = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=1e-4)

SAVE_DIR = DATASET_DIR / "checkpoints"
SAVE_DIR.mkdir(parents=True, exist_ok=True)
best_ckpt = SAVE_DIR / "unet_best.pt"

history = []
best_dice = -1.0

for epoch in range(1, EPOCHS+1):
    model.train()
    t0 = time.time()

    train_loss_sum = 0.0
    nb = 0

    for x, y, _ in train_loader:
        x = x.to(DEVICE, non_blocking=True)
        y = y.to(DEVICE, non_blocking=True)

        OPT.zero_grad(set_to_none=True)
        logits = model(x)
        loss = total_loss(logits, y, alpha=0.5)
        loss.backward()
        OPT.step()

        train_loss_sum += float(loss.item())
        nb += 1

    train_loss = train_loss_sum / max(nb,1)
    val_metrics = evaluate(model, val_loader)

    row = {"epoch": epoch, "train_loss": train_loss, **val_metrics, "sec": time.time()-t0}
    history.append(row)

    # save best
    if val_metrics["dice_mean"] > best_dice:
        best_dice = val_metrics["dice_mean"]
        torch.save({
            "epoch": epoch,
            "model_state": model.state_dict(),
            "opt_state": OPT.state_dict(),
            "best_dice": best_dice,
            "config": {
                "IMG_SIZE": IMG_SIZE, "BATCH_SIZE": BATCH_SIZE, "LR": LR, "EPOCHS": EPOCHS
            }
        }, best_ckpt)

    if epoch % 5 == 0 or epoch == 1:
        print(f"Epoch {epoch:03d} | train_loss={train_loss:.4f} | "
              f"val_loss={val_metrics['val_loss']:.4f} | "
              f"dice_outer={val_metrics['dice_outer']:.3f} dice_inner={val_metrics['dice_inner']:.3f} "
              f"mean={val_metrics['dice_mean']:.3f} | best={best_dice:.3f}")

hist_path = SAVE_DIR / "train_log.csv"
pd.DataFrame(history).to_csv(hist_path, index=False, encoding="utf-8-sig")
print("[SAVED] best ckpt ->", best_ckpt)
print("[SAVED] log       ->", hist_path)

"""##Stage 5：最佳模型在 val 做可視化疊圖（檢查邊界是否合理）

讀回 unet_best.pt

對 val set 每張圖推論出：

predicted outer mask

predicted inner mask

把「GT 輪廓」與「Pred 輪廓」疊在同一張圖上存檔，讓你用眼睛快速判斷：

邊界有沒有偏

缺口附近有沒有亂

inner 有沒有跑到 outer 外面

這步很關鍵，因為 segmentation 的數字可能好看，但邊界如果系統性偏移，你後面 thickness / gap 會整個錯。

輸入

val images

unet_best.pt

輸出（重要）

pred_overlay/*.png：每張 val 圖的疊圖（GT vs Pred）
"""

# ============================================
# Stage 5) 驗證集的視覺化推論，把模型預測的分割結果和 Ground Truth 疊在原始影像上，方便人工檢查模型表現。
# ============================================

PRED_DIR = DATASET_DIR / "pred_overlay"
PRED_DIR.mkdir(parents=True, exist_ok=True)

# load best
ckpt = torch.load(best_ckpt, map_location=DEVICE)
model.load_state_dict(ckpt["model_state"])
model.eval()
print("[INFO] loaded best epoch =", ckpt["epoch"], "best_dice =", ckpt["best_dice"])

def contour_from_mask01(mask01: np.ndarray):
    m = (mask01.astype(np.uint8) * 255)
    cnts, _ = cv2.findContours(m, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    if not cnts:
        return None
    cnt = max(cnts, key=cv2.contourArea)
    return cnt.reshape(-1, 2)

@torch.no_grad()
def infer_one(img_path: str):
    img_bgr = cv2.imread(img_path, cv2.IMREAD_COLOR)
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

    aug = val_tf(
        image=img_rgb,
        mask=np.zeros(img_rgb.shape[:2], np.uint8),
        mask2=np.zeros(img_rgb.shape[:2], np.uint8)
    )
    img_r = aug["image"]

    x = torch.from_numpy(img_r).permute(2, 0, 1).float() / 255.0
    x = x.unsqueeze(0).to(DEVICE)

    logits = model(x)
    prob = torch.sigmoid(logits)[0].detach().cpu().numpy()   # [2,H,W]

    pred_zp = (prob[0] > 0.5).astype(np.uint8)
    pred_embryo = (prob[1] > 0.5).astype(np.uint8)

    return img_r, pred_zp, pred_embryo

# 逐張 val 做疊圖
for i in range(len(val_df)):
    r = val_df.iloc[i]
    stem = r["stem"]

    # split.csv 裡存的是檔名，不是完整路徑
    img_path = str(DATASET_DIR / "images" / r["image_file"])
    gt_zp_path = str(DATASET_DIR / "masks_zp_outter" / r["zp_mask_file"])
    gt_embryo_path = str(DATASET_DIR / "masks_embryo_outer" / r["embryo_mask_file"])

    gt_zp = (cv2.imread(gt_zp_path, cv2.IMREAD_GRAYSCALE) > 127).astype(np.uint8)
    gt_embryo = (cv2.imread(gt_embryo_path, cv2.IMREAD_GRAYSCALE) > 127).astype(np.uint8)

    # resize GT to IMG_SIZE to match predictions
    gt_zp = cv2.resize(gt_zp, (IMG_SIZE, IMG_SIZE), interpolation=cv2.INTER_NEAREST)
    gt_embryo = cv2.resize(gt_embryo, (IMG_SIZE, IMG_SIZE), interpolation=cv2.INTER_NEAREST)

    img_r, pr_zp, pr_embryo = infer_one(img_path)

    # draw overlay
    vis = cv2.cvtColor(img_r, cv2.COLOR_RGB2BGR)

    # GT: cyan (thin)
    cnt = contour_from_mask01(gt_zp)
    if cnt is not None:
        cv2.polylines(vis, [cnt.astype(np.int32)], True, (255, 255, 0), 1)

    cnt = contour_from_mask01(gt_embryo)
    if cnt is not None:
        cv2.polylines(vis, [cnt.astype(np.int32)], True, (255, 255, 0), 1)

    # Pred: zp = green, embryo = red
    cnt = contour_from_mask01(pr_zp)
    if cnt is not None:
        cv2.polylines(vis, [cnt.astype(np.int32)], True, (0, 255, 0), 2)

    cnt = contour_from_mask01(pr_embryo)
    if cnt is not None:
        cv2.polylines(vis, [cnt.astype(np.int32)], True, (0, 0, 255), 2)

    cv2.imwrite(str(PRED_DIR / f"{stem}_pred_overlay.png"), vis)

print("[SAVED] overlays ->", PRED_DIR)

"""##Stage 6-0：設定推論輸出資料夾 + 讀模型"""

# ============================================
# Stage 6) inference and save predicted masks
# 輸出：
#   - masks_zp_outter
#   - masks_embryo_outer
# ============================================

from pathlib import Path
import cv2
import numpy as np
import torch
from tqdm import tqdm

ORI_DIR = Path("/content/drive/MyDrive/論文_new/need_label_ori")
PRED_ROOT = Path("/content/drive/MyDrive/論文_new/zp_pred_all_ratio")
PRED_ROOT.mkdir(parents=True, exist_ok=True)

ZP_OUT_DIR = PRED_ROOT / "masks_zp_outter"
EMBRYO_OUT_DIR = PRED_ROOT / "masks_embryo_outer"
OVERLAY_DIR = PRED_ROOT / "overlay"

ZP_OUT_DIR.mkdir(parents=True, exist_ok=True)
EMBRYO_OUT_DIR.mkdir(parents=True, exist_ok=True)
OVERLAY_DIR.mkdir(parents=True, exist_ok=True)

def cleanup_mask(mask01, keep_largest=True):
    mask01 = (mask01 > 0).astype(np.uint8)
    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(mask01, connectivity=8)
    if num_labels <= 1 or not keep_largest:
        return mask01.copy()

    areas = stats[1:, cv2.CC_STAT_AREA]
    largest_idx = 1 + int(np.argmax(areas))
    out = np.zeros_like(mask01, dtype=np.uint8)
    out[labels == largest_idx] = 1
    return out

def draw_overlay_on_image(image_rgb, zp01, embryo01):
    vis = image_rgb.copy()

    def get_cnt(mask01):
        cnts, _ = cv2.findContours((mask01 * 255).astype(np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
        if not cnts:
            return None
        return max(cnts, key=cv2.contourArea)

    cnt_zp = get_cnt(zp01)
    cnt_emb = get_cnt(embryo01)

    if cnt_zp is not None:
        cv2.drawContours(vis, [cnt_zp], -1, (0, 255, 0), 2)
    if cnt_emb is not None:
        cv2.drawContours(vis, [cnt_emb], -1, (255, 0, 0), 2)

    return vis

image_paths = []
for ext in ["*.png", "*.jpg", "*.jpeg", "*.bmp", "*.tif", "*.tiff"]:
    image_paths.extend(sorted(ORI_DIR.glob(ext)))

print("images found:", len(image_paths))

model.eval()
with torch.no_grad():
    for img_path in tqdm(image_paths):
        stem = img_path.stem

        img_bgr = cv2.imread(str(img_path))
        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
        h0, w0 = img_rgb.shape[:2]

        x = cv2.resize(img_rgb, (IMG_SIZE, IMG_SIZE))
        x = torch.from_numpy(x).permute(2, 0, 1).float().unsqueeze(0) / 255.0
        x = x.to(DEVICE)

        logits = model(x)
        probs = torch.sigmoid(logits)[0].cpu().numpy()  # [2,H,W]

        zp_pred = (probs[0] > 0.5).astype(np.uint8)
        embryo_pred = (probs[1] > 0.5).astype(np.uint8)

        zp_pred = cv2.resize(zp_pred, (w0, h0), interpolation=cv2.INTER_NEAREST)
        embryo_pred = cv2.resize(embryo_pred, (w0, h0), interpolation=cv2.INTER_NEAREST)

        zp_pred = cleanup_mask(zp_pred)
        embryo_pred = cleanup_mask(embryo_pred)

        cv2.imwrite(str(ZP_OUT_DIR / f"{stem}.png"), (zp_pred * 255).astype(np.uint8))
        cv2.imwrite(str(EMBRYO_OUT_DIR / f"{stem}.png"), (embryo_pred * 255).astype(np.uint8))

        overlay = draw_overlay_on_image(img_rgb, zp_pred, embryo_pred)
        cv2.imwrite(str(OVERLAY_DIR / f"{stem}_overlay.png"), cv2.cvtColor(overlay, cv2.COLOR_RGB2BGR))

print("Saved prediction masks to:", PRED_ROOT)

# ============================================
# Stage 7) area ratio
# 目標：
#   1) zp_outter：關閉缺口 + fill hole
#   2) embryo_outer：關閉缺口 + fill hole + 取最大連通區
#   3) 算面積與比例
#   4) 輸出到「比例」資料夾
# ============================================

from pathlib import Path
import numpy as np
import pandas as pd
import cv2
from scipy.ndimage import binary_fill_holes

PRED_ROOT = Path("/content/drive/MyDrive/論文_new/zp_pred_all_ratio")
ZP_OUTTER_DIR = PRED_ROOT / "masks_zp_outter"
EMBRYO_OUTER_DIR = PRED_ROOT / "masks_embryo_outer"

MEAS_ROOT = Path("/content/drive/MyDrive/論文_new/zp_measures_all_比例")
MEAS_ROOT.mkdir(parents=True, exist_ok=True)

ZP_CLEAN_DIR = MEAS_ROOT / "zp_outter_closed_fill_比例"
EMBRYO_CLEAN_DIR = MEAS_ROOT / "embryo_outer_closed_fill_main_比例"
OVERLAY_DIR = MEAS_ROOT / "overlay_area_ratio_比例"

ZP_CLEAN_DIR.mkdir(parents=True, exist_ok=True)
EMBRYO_CLEAN_DIR.mkdir(parents=True, exist_ok=True)
OVERLAY_DIR.mkdir(parents=True, exist_ok=True)

ZP_CLOSE_KSIZE = 9
EMBRYO_CLOSE_KSIZE = 9

def read_mask01(p):
    m = cv2.imread(str(p), cv2.IMREAD_GRAYSCALE)
    if m is None:
        raise FileNotFoundError(p)
    return (m > 127).astype(np.uint8)

def close_mask(mask01, ksize=9, iterations=1):
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (ksize, ksize))
    out = cv2.morphologyEx(mask01.astype(np.uint8), cv2.MORPH_CLOSE, kernel, iterations=iterations)
    return (out > 0).astype(np.uint8)

def fill_holes(mask01):
    return binary_fill_holes(mask01 > 0).astype(np.uint8)

def close_and_fill(mask01, ksize=9):
    return fill_holes(close_mask(mask01, ksize=ksize, iterations=1))

def keep_largest_component(mask01):
    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(mask01.astype(np.uint8), connectivity=8)
    if num_labels <= 1:
        return mask01.copy()

    areas = stats[1:, cv2.CC_STAT_AREA]
    largest_idx = 1 + int(np.argmax(areas))
    out = np.zeros_like(mask01, dtype=np.uint8)
    out[labels == largest_idx] = 1
    return out

def mask_area(mask01):
    return int((mask01 > 0).sum())

def contour_from_mask(mask01):
    cnts, _ = cv2.findContours((mask01 * 255).astype(np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    if not cnts:
        return None
    return max(cnts, key=cv2.contourArea)

def draw_overlay(zp01, embryo01):
    h, w = zp01.shape[:2]
    vis = np.zeros((h, w, 3), dtype=np.uint8)
    vis[:] = 30

    cnt_zp = contour_from_mask(zp01)
    cnt_emb = contour_from_mask(embryo01)

    if cnt_zp is not None:
        cv2.drawContours(vis, [cnt_zp], -1, (0, 255, 0), 2)
    if cnt_emb is not None:
        cv2.drawContours(vis, [cnt_emb], -1, (0, 0, 255), 2)

    return vis

zp_files = sorted(ZP_OUTTER_DIR.glob("*.png"))
print("zp_outter files:", len(zp_files))

rows = []

for zp_path in zp_files:
    stem = zp_path.stem
    embryo_path = EMBRYO_OUTER_DIR / f"{stem}.png"

    if not embryo_path.exists():
        rows.append({
            "stem": stem,
            "status": "missing_embryo_outer",
            "zp_outter_area": np.nan,
            "embryo_outer_area": np.nan,
            "embryo_to_zp_ratio": np.nan
        })
        continue

    try:
        zp01 = read_mask01(zp_path)
        embryo01 = read_mask01(embryo_path)

        zp_clean = close_and_fill(zp01, ksize=ZP_CLOSE_KSIZE)
        embryo_clean = close_and_fill(embryo01, ksize=EMBRYO_CLOSE_KSIZE)
        embryo_main = keep_largest_component(embryo_clean)

        zp_area = mask_area(zp_clean)
        embryo_area = mask_area(embryo_main)
        ratio = embryo_area / zp_area if zp_area > 0 else np.nan

        cv2.imwrite(str(ZP_CLEAN_DIR / f"{stem}.png"), (zp_clean * 255).astype(np.uint8))
        cv2.imwrite(str(EMBRYO_CLEAN_DIR / f"{stem}.png"), (embryo_main * 255).astype(np.uint8))

        overlay = draw_overlay(zp_clean, embryo_main)
        cv2.imwrite(str(OVERLAY_DIR / f"{stem}_ratio.png"), overlay)

        rows.append({
            "stem": stem,
            "status": "ok",
            "zp_outter_area": int(zp_area),
            "embryo_outer_area": int(embryo_area),
            "embryo_to_zp_ratio": float(ratio) if np.isfinite(ratio) else np.nan,
            "zp_minus_embryo_area": float(zp_area - embryo_area) if zp_area > 0 else np.nan
        })

    except Exception as e:
        rows.append({
            "stem": stem,
            "status": f"error: {str(e)}",
            "zp_outter_area": np.nan,
            "embryo_outer_area": np.nan,
            "embryo_to_zp_ratio": np.nan
        })

df_ratio = pd.DataFrame(rows)
out_csv = MEAS_ROOT / "area_ratio_summary_比例.csv"
df_ratio.to_csv(out_csv, index=False, encoding="utf-8-sig")

print("saved:", out_csv)
display(df_ratio.head(20))
print(df_ratio["status"].value_counts(dropna=False))

"""##Stage 6-1：定義推論與 QC 函數（一次寫好）"""

# ============================================
# Stage 6-1) Inference + QC helpers
# ============================================

IMG_EXTS = (".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff")

def list_images(ori_dir: str):
    files = []
    for ext in IMG_EXTS:
        files += glob.glob(str(Path(ori_dir) / f"*{ext}"))
    return sorted([Path(p) for p in files])

def preprocess_resize_rgb(img_bgr, img_size):
    # BGR -> RGB, resize to training size
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    img_r = cv2.resize(img_rgb, (img_size, img_size), interpolation=cv2.INTER_LINEAR)
    x = torch.from_numpy(img_r).permute(2,0,1).float()/255.0  # [3,H,W]
    return img_r, x

@torch.no_grad()
def infer_masks(img_bgr, img_size=512, thr=0.5):
    """
    return:
      pred_outer, pred_inner: uint8 {0,1} at img_size x img_size
    """
    img_r, x = preprocess_resize_rgb(img_bgr, img_size)
    x = x.unsqueeze(0).to(DEVICE)
    logits = model(x)
    prob = torch.sigmoid(logits)[0].detach().cpu().numpy()  # [2,H,W]
    pred_outer = (prob[0] > thr).astype(np.uint8)
    pred_inner = (prob[1] > thr).astype(np.uint8)
    return img_r, pred_outer, pred_inner

def cleanup_mask(mask01: np.ndarray, keep_largest=True):
    """
    清理小雜點：只保留最大連通區（對 outer/inner 很有用）
    """
    m = (mask01*255).astype(np.uint8)
    num, lbl, stats, _ = cv2.connectedComponentsWithStats(m, connectivity=8)
    if num <= 1:
        return mask01
    # stats: [label, x,y,w,h,area]
    areas = stats[1:, cv2.CC_STAT_AREA]
    if keep_largest:
        k = 1 + int(np.argmax(areas))
        out = (lbl == k).astype(np.uint8)
        return out
    return mask01

def qc_inner_inside_outer(outer01, inner01):
    if outer01.sum() == 0 or inner01.sum() == 0:
        return False
    outside = np.logical_and(inner01==1, outer01==0)
    return outside.sum() == 0

def qc_ring_area(outer01, inner01, min_px=200):
    ring01 = np.logical_and(outer01==1, inner01==0).astype(np.uint8)
    return int(ring01.sum()), (ring01.sum() >= min_px)

def contour_from_mask01(mask01):
    m = (mask01*255).astype(np.uint8)
    cnts, _ = cv2.findContours(m, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    if not cnts:
        return None
    cnt = max(cnts, key=cv2.contourArea)
    return cnt.reshape(-1,2)

def draw_pred_overlay(img_r_rgb, outer01, inner01):
    """
    img_r_rgb: resized RGB image (IMG_SIZE)
    outer green, inner red
    """
    vis = cv2.cvtColor(img_r_rgb, cv2.COLOR_RGB2BGR)
    cnt = contour_from_mask01(outer01)
    if cnt is not None:
        cv2.polylines(vis, [cnt.astype(np.int32)], True, (0,255,0), 2)
    cnt = contour_from_mask01(inner01)
    if cnt is not None:
        cv2.polylines(vis, [cnt.astype(np.int32)], True, (0,0,255), 2)
    return vis

"""## Stage 6-2：批次推論全資料 + 存檔 + 產生 pred_meta.csv"""

# ============================================
# Stage 6-2) Run inference on ALL images in ORI_DIR
# 輸出：
#   - masks_zp_outter
#   - masks_embryo_outer
# ============================================

from pathlib import Path
import cv2
import numpy as np
import torch
from tqdm import tqdm

ORI_DIR = Path("/content/drive/MyDrive/論文_new/need_label_ori")
PRED_ROOT = Path("/content/drive/MyDrive/論文_new/zp_pred_all_ratio")
PRED_ROOT.mkdir(parents=True, exist_ok=True)

ZP_OUT_DIR = PRED_ROOT / "masks_zp_outter"
EMBRYO_OUT_DIR = PRED_ROOT / "masks_embryo_outer"
OVERLAY_DIR = PRED_ROOT / "overlay"

ZP_OUT_DIR.mkdir(parents=True, exist_ok=True)
EMBRYO_OUT_DIR.mkdir(parents=True, exist_ok=True)
OVERLAY_DIR.mkdir(parents=True, exist_ok=True)

def cleanup_mask(mask01, keep_largest=True):
    mask01 = (mask01 > 0).astype(np.uint8)
    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(mask01, connectivity=8)
    if num_labels <= 1 or not keep_largest:
        return mask01.copy()

    areas = stats[1:, cv2.CC_STAT_AREA]
    largest_idx = 1 + int(np.argmax(areas))
    out = np.zeros_like(mask01, dtype=np.uint8)
    out[labels == largest_idx] = 1
    return out

def draw_overlay_on_image(image_rgb, zp01, embryo01):
    vis = image_rgb.copy()

    def get_cnt(mask01):
        cnts, _ = cv2.findContours((mask01 * 255).astype(np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
        if not cnts:
            return None
        return max(cnts, key=cv2.contourArea)

    cnt_zp = get_cnt(zp01)
    cnt_emb = get_cnt(embryo01)

    if cnt_zp is not None:
        cv2.drawContours(vis, [cnt_zp], -1, (0, 255, 0), 2)
    if cnt_emb is not None:
        cv2.drawContours(vis, [cnt_emb], -1, (255, 0, 0), 2)

    return vis

image_paths = []
for ext in ["*.png", "*.jpg", "*.jpeg", "*.bmp", "*.tif", "*.tiff"]:
    image_paths.extend(sorted(ORI_DIR.glob(ext)))

print("images found:", len(image_paths))

model.eval()
with torch.no_grad():
    for img_path in tqdm(image_paths):
        stem = img_path.stem

        img_bgr = cv2.imread(str(img_path))
        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
        h0, w0 = img_rgb.shape[:2]

        x = cv2.resize(img_rgb, (IMG_SIZE, IMG_SIZE))
        x = torch.from_numpy(x).permute(2, 0, 1).float().unsqueeze(0) / 255.0
        x = x.to(DEVICE)

        logits = model(x)
        probs = torch.sigmoid(logits)[0].cpu().numpy()  # [2,H,W]

        zp_pred = (probs[0] > 0.5).astype(np.uint8)
        embryo_pred = (probs[1] > 0.5).astype(np.uint8)

        zp_pred = cv2.resize(zp_pred, (w0, h0), interpolation=cv2.INTER_NEAREST)
        embryo_pred = cv2.resize(embryo_pred, (w0, h0), interpolation=cv2.INTER_NEAREST)

        zp_pred = cleanup_mask(zp_pred)
        embryo_pred = cleanup_mask(embryo_pred)

        cv2.imwrite(str(ZP_OUT_DIR / f"{stem}.png"), (zp_pred * 255).astype(np.uint8))
        cv2.imwrite(str(EMBRYO_OUT_DIR / f"{stem}.png"), (embryo_pred * 255).astype(np.uint8))

        overlay = draw_overlay_on_image(img_rgb, zp_pred, embryo_pred)
        cv2.imwrite(str(OVERLAY_DIR / f"{stem}_overlay.png"), cv2.cvtColor(overlay, cv2.COLOR_RGB2BGR))

print("Saved prediction masks to:", PRED_ROOT)

"""##Stage 7-0) Setup paths + config for area ratio
指定要讀哪個資料夾的 mask

建立新的輸出資料夾，而且名稱都有加上「比例」

設定閉運算的 kernel size
"""

# ============================================
# Stage 7-0) Setup paths + config for area ratio
# 目標：
#   1) zp_outter：關閉缺口 + fill hole
#   2) embryo_outer：關閉缺口 + fill hole + 取最大連通區
#   3) 算面積與比例
#   4) 輸出到「比例」資料夾
# ============================================

from pathlib import Path
import numpy as np
import pandas as pd
import cv2
from scipy.ndimage import binary_fill_holes

PRED_ROOT = Path("/content/drive/MyDrive/論文_new/zp_pred_all_ratio")
ZP_OUTTER_DIR = PRED_ROOT / "masks_zp_outter"
EMBRYO_OUTER_DIR = PRED_ROOT / "masks_embryo_outer"

MEAS_ROOT = Path("/content/drive/MyDrive/論文_new/zp_measures_all_比例")
MEAS_ROOT.mkdir(parents=True, exist_ok=True)

ZP_CLEAN_DIR = MEAS_ROOT / "zp_outter_closed_fill_比例"
EMBRYO_CLEAN_DIR = MEAS_ROOT / "embryo_outer_closed_fill_main_比例"
OVERLAY_DIR = MEAS_ROOT / "overlay_area_ratio_比例"

ZP_CLEAN_DIR.mkdir(parents=True, exist_ok=True)
EMBRYO_CLEAN_DIR.mkdir(parents=True, exist_ok=True)
OVERLAY_DIR.mkdir(parents=True, exist_ok=True)

ZP_CLOSE_KSIZE = 9
EMBRYO_CLOSE_KSIZE = 9

def read_mask01(p):
    m = cv2.imread(str(p), cv2.IMREAD_GRAYSCALE)
    if m is None:
        raise FileNotFoundError(p)
    return (m > 127).astype(np.uint8)

def close_mask(mask01, ksize=9, iterations=1):
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (ksize, ksize))
    out = cv2.morphologyEx(mask01.astype(np.uint8), cv2.MORPH_CLOSE, kernel, iterations=iterations)
    return (out > 0).astype(np.uint8)

def fill_holes(mask01):
    return binary_fill_holes(mask01 > 0).astype(np.uint8)

def close_and_fill(mask01, ksize=9):
    return fill_holes(close_mask(mask01, ksize=ksize, iterations=1))

def keep_largest_component(mask01):
    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(mask01.astype(np.uint8), connectivity=8)
    if num_labels <= 1:
        return mask01.copy()

    areas = stats[1:, cv2.CC_STAT_AREA]
    largest_idx = 1 + int(np.argmax(areas))
    out = np.zeros_like(mask01, dtype=np.uint8)
    out[labels == largest_idx] = 1
    return out

def mask_area(mask01):
    return int((mask01 > 0).sum())

def contour_from_mask(mask01):
    cnts, _ = cv2.findContours((mask01 * 255).astype(np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    if not cnts:
        return None
    return max(cnts, key=cv2.contourArea)

def draw_overlay(zp01, embryo01):
    h, w = zp01.shape[:2]
    vis = np.zeros((h, w, 3), dtype=np.uint8)
    vis[:] = 30

    cnt_zp = contour_from_mask(zp01)
    cnt_emb = contour_from_mask(embryo01)

    if cnt_zp is not None:
        cv2.drawContours(vis, [cnt_zp], -1, (0, 255, 0), 2)
    if cnt_emb is not None:
        cv2.drawContours(vis, [cnt_emb], -1, (0, 0, 255), 2)

    return vis

zp_files = sorted(ZP_OUTTER_DIR.glob("*.png"))
print("zp_outter files:", len(zp_files))

rows = []

for zp_path in zp_files:
    stem = zp_path.stem
    embryo_path = EMBRYO_OUTER_DIR / f"{stem}.png"

    if not embryo_path.exists():
        rows.append({
            "stem": stem,
            "status": "missing_embryo_outer",
            "zp_outter_area": np.nan,
            "embryo_outer_area": np.nan,
            "embryo_to_zp_ratio": np.nan
        })
        continue

    try:
        zp01 = read_mask01(zp_path)
        embryo01 = read_mask01(embryo_path)

        zp_clean = close_and_fill(zp01, ksize=ZP_CLOSE_KSIZE)
        embryo_clean = close_and_fill(embryo01, ksize=EMBRYO_CLOSE_KSIZE)
        embryo_main = keep_largest_component(embryo_clean)

        zp_area = mask_area(zp_clean)
        embryo_area = mask_area(embryo_main)
        ratio = embryo_area / zp_area if zp_area > 0 else np.nan

        cv2.imwrite(str(ZP_CLEAN_DIR / f"{stem}.png"), (zp_clean * 255).astype(np.uint8))
        cv2.imwrite(str(EMBRYO_CLEAN_DIR / f"{stem}.png"), (embryo_main * 255).astype(np.uint8))

        overlay = draw_overlay(zp_clean, embryo_main)
        cv2.imwrite(str(OVERLAY_DIR / f"{stem}_ratio.png"), overlay)

        rows.append({
            "stem": stem,
            "status": "ok",
            "zp_outter_area": int(zp_area),
            "embryo_outer_area": int(embryo_area),
            "embryo_to_zp_ratio": float(ratio) if np.isfinite(ratio) else np.nan,
            "zp_minus_embryo_area": float(zp_area - embryo_area) if zp_area > 0 else np.nan
        })

    except Exception as e:
        rows.append({
            "stem": stem,
            "status": f"error: {str(e)}",
            "zp_outter_area": np.nan,
            "embryo_outer_area": np.nan,
            "embryo_to_zp_ratio": np.nan
        })

df_ratio = pd.DataFrame(rows)
out_csv = MEAS_ROOT / "area_ratio_summary_比例.csv"
df_ratio.to_csv(out_csv, index=False, encoding="utf-8-sig")

print("saved:", out_csv)
display(df_ratio.head(20))
print(df_ratio["status"].value_counts(dropna=False))

"""## Stage 7-1) Helper functions for area ratio"""

# ============================================
# Stage 7-1) Helper functions for area ratio
# 目標：
#   1) 讀 mask
#   2) 關閉缺口（morph close）
#   3) fill hole
#   4) embryo_outer 保留最大連通區
#   5) 畫疊圖檢查結果
# ============================================

def read_mask01(p: Path) -> np.ndarray:
    """
    讀灰階 mask，轉成 0/1
    """
    m = cv2.imread(str(p), cv2.IMREAD_GRAYSCALE)
    if m is None:
        raise FileNotFoundError(p)
    return (m > 127).astype(np.uint8)

def close_mask(mask01: np.ndarray, ksize: int = 9, iterations: int = 1) -> np.ndarray:
    """
    閉運算：
    先膨脹再侵蝕，用來關閉小缺口、補小裂縫
    """
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (ksize, ksize))
    out = cv2.morphologyEx(mask01.astype(np.uint8), cv2.MORPH_CLOSE, kernel, iterations=iterations)
    return (out > 0).astype(np.uint8)

def fill_holes(mask01: np.ndarray) -> np.ndarray:
    """
    填滿內部孔洞
    """
    filled = binary_fill_holes(mask01 > 0)
    return filled.astype(np.uint8)

def close_and_fill(mask01: np.ndarray, ksize: int = 9, iterations: int = 1) -> np.ndarray:
    """
    先關閉缺口，再 fill hole
    """
    closed = close_mask(mask01, ksize=ksize, iterations=iterations)
    filled = fill_holes(closed)
    return filled.astype(np.uint8)

def keep_largest_component(mask01: np.ndarray) -> np.ndarray:
    """
    只保留最大連通區
    適合 embryo_outer，避免小雜點被一起算進面積
    """
    mask01 = (mask01 > 0).astype(np.uint8)
    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(mask01, connectivity=8)

    if num_labels <= 1:
        return mask01.copy()

    areas = stats[1:, cv2.CC_STAT_AREA]   # 跳過背景 0
    largest_idx = 1 + int(np.argmax(areas))

    out = np.zeros_like(mask01, dtype=np.uint8)
    out[labels == largest_idx] = 1
    return out

def mask_area(mask01: np.ndarray) -> int:
    """
    計算 mask 面積（像素數）
    """
    return int((mask01 > 0).sum())

def contour_from_mask01(mask01: np.ndarray):
    """
    從 mask 取最大外輪廓，用來畫 overlay
    """
    m = (mask01 * 255).astype(np.uint8)
    cnts, _ = cv2.findContours(m, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    if not cnts:
        return None
    cnt = max(cnts, key=cv2.contourArea)
    return cnt.reshape(-1, 2)

def draw_area_overlay(zp01: np.ndarray, embryo01: np.ndarray) -> np.ndarray:
    """
    畫面積比例 QC 疊圖：
      - zp_outer：綠線
      - embryo_outer：紅線
    背景用深灰方便看
    """
    h, w = zp01.shape[:2]
    vis = np.zeros((h, w, 3), dtype=np.uint8)
    vis[:] = 30  # 深灰背景

    cnt_zp = contour_from_mask01(zp01)
    cnt_em = contour_from_mask01(embryo01)

    if cnt_zp is not None:
        cv2.polylines(vis, [cnt_zp.astype(np.int32)], True, (0, 255, 0), 2)   # 綠
    if cnt_em is not None:
        cv2.polylines(vis, [cnt_em.astype(np.int32)], True, (0, 0, 255), 2)   # 紅

    return vis

def compute_area_ratio_metrics(zp_outer01: np.ndarray, embryo_outer01: np.ndarray,
                               zp_close_ksize: int = 9, embryo_close_ksize: int = 9):
    """
    核心量測函數：
      1) zp_outer：關閉缺口 + fill hole
      2) embryo_outer：關閉缺口 + fill hole + 保留最大連通區
      3) 算面積與比例
    """
    # ZP outer：閉運算 + 補洞
    zp_clean = close_and_fill(zp_outer01, ksize=zp_close_ksize, iterations=1)

    # Embryo outer：閉運算 + 補洞 + 主體保留
    embryo_clean = close_and_fill(embryo_outer01, ksize=embryo_close_ksize, iterations=1)
    embryo_main = keep_largest_component(embryo_clean)

    # 面積
    zp_area = mask_area(zp_clean)
    embryo_area = mask_area(embryo_main)

    # 比例
    ratio = embryo_area / zp_area if zp_area > 0 else np.nan
    remain_area = zp_area - embryo_area if zp_area > 0 else np.nan

    return {
        "zp_clean": zp_clean,
        "embryo_main": embryo_main,
        "zp_outer_area": zp_area,
        "embryo_outer_area": embryo_area,
        "embryo_to_zp_ratio": ratio,
        "zp_minus_embryo_area": remain_area,
    }

# ============================================
# Stage 7-2) Batch: area metrics + ratio + overlays
# 目標：
#   1) zp_outter：關閉缺口 + fill hole
#   2) embryo_outer：關閉缺口 + fill hole + 取最大連通區
#   3) 算面積與比例
#   4) 輸出到「比例」資料夾
# ============================================

from pathlib import Path
import numpy as np
import pandas as pd
import cv2
from scipy.ndimage import binary_fill_holes

PRED_ROOT = Path("/content/drive/MyDrive/論文_new/zp_pred_all_ratio")
ZP_OUTTER_DIR = PRED_ROOT / "masks_zp_outter"
EMBRYO_OUTER_DIR = PRED_ROOT / "masks_embryo_outer"

MEAS_ROOT = Path("/content/drive/MyDrive/論文_new/zp_measures_all_比例")
MEAS_ROOT.mkdir(parents=True, exist_ok=True)

ZP_CLEAN_DIR = MEAS_ROOT / "zp_outter_closed_fill_比例"
EMBRYO_CLEAN_DIR = MEAS_ROOT / "embryo_outer_closed_fill_main_比例"
OVERLAY_DIR = MEAS_ROOT / "overlay_area_ratio_比例"

ZP_CLEAN_DIR.mkdir(parents=True, exist_ok=True)
EMBRYO_CLEAN_DIR.mkdir(parents=True, exist_ok=True)
OVERLAY_DIR.mkdir(parents=True, exist_ok=True)

ZP_CLOSE_KSIZE = 9
EMBRYO_CLOSE_KSIZE = 9

def read_mask01(p):
    m = cv2.imread(str(p), cv2.IMREAD_GRAYSCALE)
    if m is None:
        raise FileNotFoundError(p)
    return (m > 127).astype(np.uint8)

def close_mask(mask01, ksize=9, iterations=1):
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (ksize, ksize))
    out = cv2.morphologyEx(mask01.astype(np.uint8), cv2.MORPH_CLOSE, kernel, iterations=iterations)
    return (out > 0).astype(np.uint8)

def fill_holes(mask01):
    return binary_fill_holes(mask01 > 0).astype(np.uint8)

def close_and_fill(mask01, ksize=9):
    return fill_holes(close_mask(mask01, ksize=ksize, iterations=1))

def keep_largest_component(mask01):
    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(mask01.astype(np.uint8), connectivity=8)
    if num_labels <= 1:
        return mask01.copy()

    areas = stats[1:, cv2.CC_STAT_AREA]
    largest_idx = 1 + int(np.argmax(areas))
    out = np.zeros_like(mask01, dtype=np.uint8)
    out[labels == largest_idx] = 1
    return out

def mask_area(mask01):
    return int((mask01 > 0).sum())

def contour_from_mask(mask01):
    cnts, _ = cv2.findContours((mask01 * 255).astype(np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    if not cnts:
        return None
    return max(cnts, key=cv2.contourArea)

def draw_overlay(zp01, embryo01):
    h, w = zp01.shape[:2]
    vis = np.zeros((h, w, 3), dtype=np.uint8)
    vis[:] = 30

    cnt_zp = contour_from_mask(zp01)
    cnt_emb = contour_from_mask(embryo01)

    if cnt_zp is not None:
        cv2.drawContours(vis, [cnt_zp], -1, (0, 255, 0), 2)
    if cnt_emb is not None:
        cv2.drawContours(vis, [cnt_emb], -1, (0, 0, 255), 2)

    return vis

zp_files = sorted(ZP_OUTTER_DIR.glob("*.png"))
print("zp_outter files:", len(zp_files))

rows = []

for zp_path in zp_files:
    stem = zp_path.stem
    embryo_path = EMBRYO_OUTER_DIR / f"{stem}.png"

    if not embryo_path.exists():
        rows.append({
            "stem": stem,
            "status": "missing_embryo_outer",
            "zp_outter_area": np.nan,
            "embryo_outer_area": np.nan,
            "embryo_to_zp_ratio": np.nan
        })
        continue

    try:
        zp01 = read_mask01(zp_path)
        embryo01 = read_mask01(embryo_path)

        zp_clean = close_and_fill(zp01, ksize=ZP_CLOSE_KSIZE)
        embryo_clean = close_and_fill(embryo01, ksize=EMBRYO_CLOSE_KSIZE)
        embryo_main = keep_largest_component(embryo_clean)

        zp_area = mask_area(zp_clean)
        embryo_area = mask_area(embryo_main)
        ratio = embryo_area / zp_area if zp_area > 0 else np.nan

        cv2.imwrite(str(ZP_CLEAN_DIR / f"{stem}.png"), (zp_clean * 255).astype(np.uint8))
        cv2.imwrite(str(EMBRYO_CLEAN_DIR / f"{stem}.png"), (embryo_main * 255).astype(np.uint8))

        overlay = draw_overlay(zp_clean, embryo_main)
        cv2.imwrite(str(OVERLAY_DIR / f"{stem}_ratio.png"), overlay)

        rows.append({
            "stem": stem,
            "status": "ok",
            "zp_outter_area": int(zp_area),
            "embryo_outer_area": int(embryo_area),
            "embryo_to_zp_ratio": float(ratio) if np.isfinite(ratio) else np.nan,
            "zp_minus_embryo_area": float(zp_area - embryo_area) if zp_area > 0 else np.nan
        })

    except Exception as e:
        rows.append({
            "stem": stem,
            "status": f"error: {str(e)}",
            "zp_outter_area": np.nan,
            "embryo_outer_area": np.nan,
            "embryo_to_zp_ratio": np.nan
        })

df_ratio = pd.DataFrame(rows)
out_csv = MEAS_ROOT / "area_ratio_summary_比例.csv"
df_ratio.to_csv(out_csv, index=False, encoding="utf-8-sig")

print("saved:", out_csv)
display(df_ratio.head(20))
print(df_ratio["status"].value_counts(dropna=False))

from google.colab import runtime
runtime.unassign()